apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: a41vbpkhk-java-quarkus-gitops-repository
spec:
  url: https://github.com/chetna14manku-org/a41vbpkhk-java-quarkus-gitops